In [1]:
import numpy as np
from run_length import *

# Testing

In [8]:
test = np.array([[16,16,3,3],
                    [16,16,3,0],
                    [16,3,0,0],
                    [16,0,0,0]])

matrix = np.array([[16,  16,  16,  16,  24,  40,  51,  0], 
                    [16,  16,  16,  19,  26,  58,  0,  0],
                    [16,  16,  16,  24,  40,  57,  0,  0], 
                    [14,  17,  22,  29,  51,  0,  0,  0], 
                    [18,  22,  37,  56,  68, 0, 0,  0], 
                    [24,  35,  0,  0,  0, 0, 0,  0], 
                    [49,  64,  0,  0, 0, 0, 0, 0], 
                    [72,  92,  0,  0, 0, 0, 0,  0]])

In [9]:
result = zigzag_iteration(matrix)
print(result)

[16, 16, 16, 16, 16, 16, 16, 16, 16, 14, 18, 17, 16, 19, 24, 40, 26, 24, 22, 22, 24, 49, 35, 37, 29, 40, 58, 51, 0, 0, 57, 51, 56, 0, 64, 72, 92, 0, 0, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [10]:
run_length_code_binary = run_length_coding_binary(result)
print(run_length_code_binary)

[('00010000', '00001001'), ('00001110', '00000001'), ('00010010', '00000001'), ('00010001', '00000001'), ('00010000', '00000001'), ('00010011', '00000001'), ('00011000', '00000001'), ('00101000', '00000001'), ('00011010', '00000001'), ('00011000', '00000001'), ('00010110', '00000010'), ('00011000', '00000001'), ('00110001', '00000001'), ('00100011', '00000001'), ('00100101', '00000001'), ('00011101', '00000001'), ('00101000', '00000001'), ('00111010', '00000001'), ('00110011', '00000001'), ('00000000', '00000010'), ('00111001', '00000001'), ('00110011', '00000001'), ('00111000', '00000001'), ('00000000', '00000001'), ('01000000', '00000001'), ('01001000', '00000001'), ('01011100', '00000001'), ('00000000', '00000010'), ('01000100', '00000001'), ('00000000', '00011000')]


In [11]:
bit_sequence = get_bit_sequence(run_length_code_binary)
print(bit_sequence)

000100000000100100001110000000010001001000000001000100010000000100010000000000010001001100000001000110000000000100101000000000010001101000000001000110000000000100010110000000100001100000000001001100010000000100100011000000010010010100000001000111010000000100101000000000010011101000000001001100110000000100000000000000100011100100000001001100110000000100111000000000010000000000000001010000000000000101001000000000010101110000000001000000000000001001000100000000010000000000011000


In [12]:
result = decode_run_length(bit_sequence)
print(result)

[16, 16, 16, 16, 16, 16, 16, 16, 16, 14, 18, 17, 16, 19, 24, 40, 26, 24, 22, 22, 24, 49, 35, 37, 29, 40, 58, 51, 0, 0, 57, 51, 56, 0, 64, 72, 92, 0, 0, 68, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [15]:
decoded = np.array(recreate_matrix_from_zigzag(result, 8, 8))
print(decoded)

[[16 16 16 16 24 40 51  0]
 [16 16 16 19 26 58  0  0]
 [16 16 16 24 40 57  0  0]
 [14 17 22 29 51  0  0  0]
 [18 22 37 56 68  0  0  0]
 [24 35  0  0  0  0  0  0]
 [49 64  0  0  0  0  0  0]
 [72 92  0  0  0  0  0  0]]


In [18]:
print(matrix)

[[16 16 16 16 24 40 51  0]
 [16 16 16 19 26 58  0  0]
 [16 16 16 24 40 57  0  0]
 [14 17 22 29 51  0  0  0]
 [18 22 37 56 68  0  0  0]
 [24 35  0  0  0  0  0  0]
 [49 64  0  0  0  0  0  0]
 [72 92  0  0  0  0  0  0]]
